<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admin</name>
   <tag></tag>
   <elementGuidId>3b586472-76f7-4a57-a1fd-c10dbf917ec0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>48258402-c697-4631-9147-68821705997e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center ng-star-inserted</value>
      <webElementGuid>e031fbef-6062-448b-8563-3e7edf705517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>4eefc8ae-6eec-4b57-b0d1-785afb96bfeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/dashboard</value>
      <webElementGuid>7dd09d6f-6d92-4ec7-a1d7-7a9e581c7094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>5adf3033-3006-48ac-8d8d-6607256eb6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-open&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/core-sidebar[@class=&quot;main-menu menu-fixed menu-accordio menu-shadow menu-light ng-star-inserted&quot;]/app-menu[@class=&quot;vertical-menu&quot;]/vertical-menu[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-menu-content ps&quot;]/ul[@class=&quot;navigation navigation-main&quot;]/li[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;d-flex align-items-center ng-star-inserted&quot;]</value>
      <webElementGuid>2e01d186-57e7-4065-bce1-b62735c7185e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4a189f0b-3251-4d05-9346-c6ef410c6858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center ng-star-inserted</value>
      <webElementGuid>261c7325-a729-4bc3-8806-58b525dec90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>e1b3ba21-7ed0-4908-a147-c8749aa6394d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/dashboard</value>
      <webElementGuid>66143102-e241-4745-bb23-4de20e15606a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>bb63da7a-f04a-4ec4-a6a6-5b9b97b2e5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-open&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/core-sidebar[@class=&quot;main-menu menu-fixed menu-accordio menu-shadow menu-light ng-star-inserted&quot;]/app-menu[@class=&quot;vertical-menu&quot;]/vertical-menu[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-menu-content ps&quot;]/ul[@class=&quot;navigation navigation-main&quot;]/li[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;d-flex align-items-center ng-star-inserted&quot;]</value>
      <webElementGuid>56188bf6-06ac-4c91-b415-48e4bcdbfc27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c9490f67-2afe-47a9-a727-480f14bbfa3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center ng-star-inserted</value>
      <webElementGuid>825863ee-86a1-40dd-8b5d-d857e8ed975b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>05367bd4-8958-45c6-a83b-18bc76b02e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/dashboard</value>
      <webElementGuid>e152827b-7b8f-4565-9c26-5955ba7ab88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>646a45b2-c2d5-4d15-9ee8-eb203869d9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-open&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/core-sidebar[@class=&quot;main-menu menu-fixed menu-accordio menu-shadow menu-light ng-star-inserted&quot;]/app-menu[@class=&quot;vertical-menu&quot;]/vertical-menu[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-menu-content ps&quot;]/ul[@class=&quot;navigation navigation-main&quot;]/li[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;d-flex align-items-center ng-star-inserted&quot;]</value>
      <webElementGuid>86fb1023-de4e-4727-a645-49e8ec843751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>79fa7b9c-2b28-4d02-9e97-a215e4d283ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center ng-star-inserted</value>
      <webElementGuid>734981f4-5847-40c4-8132-50cc2086608f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>ea0b3d13-9a01-42a3-ad9d-6d4b23e8ca2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/dashboard</value>
      <webElementGuid>57bfd23c-86c3-4715-a606-de04b6be0670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>f62d7430-ff9c-492c-a198-08b6b32d6195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-open&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/core-sidebar[@class=&quot;main-menu menu-fixed menu-accordio menu-shadow menu-light ng-star-inserted&quot;]/app-menu[@class=&quot;vertical-menu&quot;]/vertical-menu[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-menu-content ps&quot;]/ul[@class=&quot;navigation navigation-main&quot;]/li[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;d-flex align-items-center ng-star-inserted&quot;]</value>
      <webElementGuid>358b8d9c-5e1e-4c6c-a969-cf25ca87354b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed533b1d-cb1a-4cda-b061-62c10194be88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center ng-star-inserted</value>
      <webElementGuid>c03409a3-dbe0-49e5-9c6c-23fa607b4855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>44531f3c-720a-4ec5-91f2-1f46eeb8c67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/dashboard</value>
      <webElementGuid>e3a951bf-2e31-4048-9499-73cfcaab65d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>9e5c51fd-2a60-4f24-a417-68a56f04cc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-open&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/core-sidebar[@class=&quot;main-menu menu-fixed menu-accordio menu-shadow menu-light ng-star-inserted&quot;]/app-menu[@class=&quot;vertical-menu&quot;]/vertical-menu[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-menu-content ps&quot;]/ul[@class=&quot;navigation navigation-main&quot;]/li[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;d-flex align-items-center ng-star-inserted&quot;]</value>
      <webElementGuid>b133f741-e346-441f-90da-320ce8f14d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b3e64c1e-9590-455b-bf61-a1a2900dab48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center ng-star-inserted</value>
      <webElementGuid>cf676a42-7503-47f4-9a4a-184eb6bea440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>4edcd245-5006-433a-a87b-88693d7a2a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/dashboard</value>
      <webElementGuid>c3363d3d-738c-4292-a80f-b8257c9c37af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>24f1b5ec-0070-4699-ba47-29d546a62a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-open&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/core-sidebar[@class=&quot;main-menu menu-fixed menu-accordio menu-shadow menu-light ng-star-inserted&quot;]/app-menu[@class=&quot;vertical-menu&quot;]/vertical-menu[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-menu-content ps&quot;]/ul[@class=&quot;navigation navigation-main&quot;]/li[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;d-flex align-items-center ng-star-inserted&quot;]</value>
      <webElementGuid>1df64217-3c4d-4493-90bc-6bbc759fba41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>3eba57c3-69f4-44a7-b296-b508ab6322ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ICE'])[1]/following::a[4]</value>
      <webElementGuid>3bb75bd1-f5d8-4347-8f81-e71962a55981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Storage'])[1]/preceding::a[1]</value>
      <webElementGuid>4f5f0d5d-f2cc-4de7-bfe8-7b136b1f28cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/dashboard')]</value>
      <webElementGuid>b29b406e-fc31-4795-8de5-3622b629c9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[2]/a</value>
      <webElementGuid>b5710da6-96a9-4d89-954b-aed9fd10ac2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/dashboard' and (text() = 'Admin' or . = 'Admin')]</value>
      <webElementGuid>8e88e18e-c901-4ae9-a9b2-cf9f9a2421a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
