<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Next</name>
   <tag></tag>
   <elementGuidId>78093bd0-814c-418e-abc5-f031a48eab75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Next')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>29e9ad3c-2a4d-4a3e-a247-e6558f742fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>05592b5f-aa4a-494e-8ba0-b587be9f0671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link</value>
      <webElementGuid>1b592df0-8857-43bd-8af3-8ba6a4f60e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>8a3ee7eb-31ef-434a-ad00-70874ed264ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-hide&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-content content&quot;]/content[@class=&quot;ng-tns-c118-1 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c118-1 ng-trigger ng-trigger-zoomIn&quot;]/app-user-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content-wrapper container-xxl p-0&quot;]/div[@class=&quot;content-body&quot;]/section[@class=&quot;users-list-wrapper&quot;]/div[@class=&quot;card mb-3 lg-3 xs-3&quot;]/div[@class=&quot;table-responsive&quot;]/div[@class=&quot;d-flex justify-content-between align-items-center m-1&quot;]/ngb-pagination[1]/ul[@class=&quot;pagination&quot;]/li[@class=&quot;page-item ng-star-inserted&quot;]/a[@class=&quot;page-link&quot;]</value>
      <webElementGuid>37251f65-258f-4b28-a276-31a79062e538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4177696c-ac67-4a85-a699-559db30bd7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>0eb28d1d-3666-4bc5-8e4f-64781e181158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link</value>
      <webElementGuid>34d0a1c7-482a-480e-89d7-09e6cc098646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>fa2eeee5-54d6-466a-b849-02c88f17aaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-hide&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-content content&quot;]/content[@class=&quot;ng-tns-c118-1 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c118-1 ng-trigger ng-trigger-zoomIn&quot;]/app-user-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content-wrapper container-xxl p-0&quot;]/div[@class=&quot;content-body&quot;]/section[@class=&quot;users-list-wrapper&quot;]/div[@class=&quot;card mb-3 lg-3 xs-3&quot;]/div[@class=&quot;table-responsive&quot;]/div[@class=&quot;d-flex justify-content-between align-items-center m-1&quot;]/ngb-pagination[1]/ul[@class=&quot;pagination&quot;]/li[@class=&quot;page-item ng-star-inserted&quot;]/a[@class=&quot;page-link&quot;]</value>
      <webElementGuid>0393c495-49c0-489e-b036-40ba1295b20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>64d86f78-88e2-4f6e-94f2-36474f63a182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>ba6205c4-50fb-4178-80e1-4106291e5554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link</value>
      <webElementGuid>015778dc-9d2c-4500-a4e0-778b817c8789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>a1399cf4-9189-4274-bb8a-c95fa48b8f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-hide&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-content content&quot;]/content[@class=&quot;ng-tns-c118-1 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c118-1 ng-trigger ng-trigger-zoomIn&quot;]/app-user-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content-wrapper container-xxl p-0&quot;]/div[@class=&quot;content-body&quot;]/section[@class=&quot;users-list-wrapper&quot;]/div[@class=&quot;card mb-3 lg-3 xs-3&quot;]/div[@class=&quot;table-responsive&quot;]/div[@class=&quot;d-flex justify-content-between align-items-center m-1&quot;]/ngb-pagination[1]/ul[@class=&quot;pagination&quot;]/li[@class=&quot;page-item ng-star-inserted&quot;]/a[@class=&quot;page-link&quot;]</value>
      <webElementGuid>680dd1b4-878b-4998-9056-0ffebad4347f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Next')]</value>
      <webElementGuid>d2bf0ca3-4ca1-4817-8cc3-a4230bf6214c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(current)'])[1]/following::a[2]</value>
      <webElementGuid>746e53c3-7330-4e41-8b1d-cf9df3313f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev'])[1]/following::a[3]</value>
      <webElementGuid>ed55cbb9-5c96-4bf7-b02e-143738fbcfd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last'])[1]/preceding::a[1]</value>
      <webElementGuid>6c8f3411-f248-4bd8-ac92-3b39e26d609b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>893810e8-8303-448f-95a3-764d7bf0fba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[40]</value>
      <webElementGuid>0b07f983-5096-4768-9d7b-9ca5869fff95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ngb-pagination/ul/li[5]/a</value>
      <webElementGuid>b76ea640-625a-44d1-8107-828145914e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>27558372-ab32-44f3-95a5-31277e584512</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
