<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Users</name>
   <tag></tag>
   <elementGuidId>bd1e7e5b-2b5a-42c5-9eaa-a584489fca14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Storage'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2367433a-19b3-47c9-9279-298bbd6af385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center ng-star-inserted</value>
      <webElementGuid>e61e8a24-3a8a-43d7-b29f-80a319c9821a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>fe5927eb-d5f0-438a-9f64-9bd69da8a557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/user/userlist</value>
      <webElementGuid>0fe40c5a-dbcd-46db-8d3a-a87a0618d3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users</value>
      <webElementGuid>3cfeca2c-0920-4d68-8c0a-05b84933f21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-open&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/core-sidebar[@class=&quot;main-menu menu-fixed menu-accordio menu-shadow menu-light ng-star-inserted&quot;]/app-menu[@class=&quot;vertical-menu&quot;]/vertical-menu[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-menu-content ps&quot;]/ul[@class=&quot;navigation navigation-main&quot;]/li[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;d-flex align-items-center ng-star-inserted&quot;]</value>
      <webElementGuid>a07a1917-9cdf-4006-9936-ebfa89a3fdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>036c592f-3f59-4b3b-b758-d1a93ef4b5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center ng-star-inserted</value>
      <webElementGuid>8db00ea0-babe-491d-9e09-a5ecd6b269d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>68f3a278-5e2b-4ba9-88ca-5d021f31611d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/user/userlist</value>
      <webElementGuid>ccf99324-e8d4-4826-9095-506604d2b4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users</value>
      <webElementGuid>a2c24184-691e-4bfb-a723-6d7c04f51c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-open&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/core-sidebar[@class=&quot;main-menu menu-fixed menu-accordio menu-shadow menu-light ng-star-inserted&quot;]/app-menu[@class=&quot;vertical-menu&quot;]/vertical-menu[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-menu-content ps&quot;]/ul[@class=&quot;navigation navigation-main&quot;]/li[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;d-flex align-items-center ng-star-inserted&quot;]</value>
      <webElementGuid>18dac9f7-9ef9-460b-8f17-e74f2be63aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32ea94c2-3e7a-4489-90dc-1b32015bb335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center ng-star-inserted</value>
      <webElementGuid>651c1d14-79fe-400d-9ae6-c3984ebc1460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>b9ad5b51-7cd7-4b70-81b5-00d4d3cd298e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/user/userlist</value>
      <webElementGuid>1463ff70-495f-4c67-8813-4dfa80298a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users</value>
      <webElementGuid>32ff90bf-5c62-4d8c-aff1-4d3d5f42c1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-open&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/core-sidebar[@class=&quot;main-menu menu-fixed menu-accordio menu-shadow menu-light ng-star-inserted&quot;]/app-menu[@class=&quot;vertical-menu&quot;]/vertical-menu[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-menu-content ps&quot;]/ul[@class=&quot;navigation navigation-main&quot;]/li[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;d-flex align-items-center ng-star-inserted&quot;]</value>
      <webElementGuid>490e149a-74c5-4f05-8a1f-24c7327f9296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d07b6a79-a7a8-4701-9708-09249bab7c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center ng-star-inserted</value>
      <webElementGuid>810e49a4-ec6e-4ecc-a763-60475f218d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>48b91401-8d63-47a3-bce7-6be580031dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/user/userlist</value>
      <webElementGuid>f7d3ab84-cd77-4704-a652-1fd893240fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users</value>
      <webElementGuid>ea429c30-f51b-4abb-bb96-4f9910e6da2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-open&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/core-sidebar[@class=&quot;main-menu menu-fixed menu-accordio menu-shadow menu-light ng-star-inserted&quot;]/app-menu[@class=&quot;vertical-menu&quot;]/vertical-menu[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-menu-content ps&quot;]/ul[@class=&quot;navigation navigation-main&quot;]/li[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;d-flex align-items-center ng-star-inserted&quot;]</value>
      <webElementGuid>0b2f2bc8-e180-4be4-8769-7a2d9edc8f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b08ef751-66d4-430c-a651-7695a3fcbfb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center ng-star-inserted</value>
      <webElementGuid>271e2cca-eda2-4b35-8469-1ba731cfe435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>18783631-d348-4f89-8389-f9365593ccc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/user/userlist</value>
      <webElementGuid>49b3f60c-3e80-476f-a788-200b29f18cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users</value>
      <webElementGuid>c1ec375c-2c37-4da5-95d7-360988f14445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-open&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/core-sidebar[@class=&quot;main-menu menu-fixed menu-accordio menu-shadow menu-light ng-star-inserted&quot;]/app-menu[@class=&quot;vertical-menu&quot;]/vertical-menu[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-menu-content ps&quot;]/ul[@class=&quot;navigation navigation-main&quot;]/li[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;d-flex align-items-center ng-star-inserted&quot;]</value>
      <webElementGuid>d8dde783-d791-4ad5-86ef-6f078532693a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Storage'])[1]/following::a[1]</value>
      <webElementGuid>24f4b7c4-6591-4d91-b970-72220fa3234e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::a[2]</value>
      <webElementGuid>9ecb3fdf-e903-4b55-8d54-605150dbefe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vcf'])[1]/preceding::a[1]</value>
      <webElementGuid>3fe22f20-bca3-4888-9b1f-9275913ab530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/user/userlist')]</value>
      <webElementGuid>d6910c85-9bdc-435d-b8e4-f3d3f215de25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[4]/a</value>
      <webElementGuid>2ecc80da-f1d8-4f7c-a15c-bca391390768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/user/userlist' and (text() = 'Users' or . = 'Users')]</value>
      <webElementGuid>d346f1d0-738d-4037-8e16-74fe9b72c3b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
