<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update</name>
   <tag></tag>
   <elementGuidId>fb46be03-48f5-4eb6-abb3-a2335638e7f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='row']/div[10]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-group > button.btn.btn-primary.waves-effect.waves-float.waves-light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c6128304-ffc1-44b9-b553-86c232aceacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary waves-effect waves-float waves-light</value>
      <webElementGuid>24c6e01c-df20-409a-ab8f-a3b76b77eec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update </value>
      <webElementGuid>9e183a14-5a93-4af0-9c1a-54d28122beaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row&quot;)/div[@class=&quot;col-12 text-center&quot;]/div[@class=&quot;form-group&quot;]/button[@class=&quot;btn btn-primary waves-effect waves-float waves-light&quot;]</value>
      <webElementGuid>9c2d792c-586e-43cc-8c1f-fd8beebcb498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ecf6ffe0-68d0-400b-922c-79e8d5108564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary waves-effect waves-float waves-light</value>
      <webElementGuid>76108832-f132-4cfb-9b6b-7778fef449ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update </value>
      <webElementGuid>0166b010-4090-4b98-95f1-c77daa0acb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row&quot;)/div[@class=&quot;col-12 text-center&quot;]/div[@class=&quot;form-group&quot;]/button[@class=&quot;btn btn-primary waves-effect waves-float waves-light&quot;]</value>
      <webElementGuid>2019d947-9b34-429f-bfd3-5ab9aa566c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d74222d9-a9e9-4a62-8646-dc7fd66e455b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary waves-effect waves-float waves-light</value>
      <webElementGuid>21ea68e3-2bc2-4006-8967-9e510b1ef332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update </value>
      <webElementGuid>1049cc36-e6d5-40d1-a75a-7cb738c0af49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row&quot;)/div[@class=&quot;col-12 text-center&quot;]/div[@class=&quot;form-group&quot;]/button[@class=&quot;btn btn-primary waves-effect waves-float waves-light&quot;]</value>
      <webElementGuid>0d223dea-8f08-40dc-829f-2e1eeb97bdc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='row']/div[10]/div/button</value>
      <webElementGuid>3b4d7066-6862-429f-9a93-c3002ce4dff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZipCode'])[1]/following::button[1]</value>
      <webElementGuid>1a8000bd-8ff6-4a6f-b065-ed47204eeb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::button[1]</value>
      <webElementGuid>495a3589-2215-4c34-b7a6-0d814744cd14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update']/parent::*</value>
      <webElementGuid>42e77e0c-27b8-452f-8923-2c4e46a6dcc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/button</value>
      <webElementGuid>ea6f17d4-1277-4095-a66f-c640c45cd3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Update ' or . = 'Update ')]</value>
      <webElementGuid>c8e46c54-1da1-4160-bc80-a75a688ee8bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
