<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ORSelect filesChoose file</name>
   <tag></tag>
   <elementGuidId>36b01f34-1e52-40f3-83f6-555e71d9c56a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='row2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#row2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>759d0650-0099-4dd7-883e-c21c5af2b478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>row2</value>
      <webElementGuid>bf029539-f1bf-437e-8ecd-65d541730605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ORSelect filesChoose file</value>
      <webElementGuid>292db253-bd9b-4de6-af40-6cb2e4209675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row2&quot;)</value>
      <webElementGuid>adfe8cb0-8491-4045-b1c1-d050d765c6f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='row2']</value>
      <webElementGuid>4eef5bc7-ba4d-472d-9d41-f8fd52ff3200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='file-upload']/div/div/div/div[2]/div[2]</value>
      <webElementGuid>459611fc-9538-4da3-838c-d98d37d9fd0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drop Files Here To Upload'])[1]/following::div[1]</value>
      <webElementGuid>dd20892f-3d74-4d25-a0f8-39bdcd19af31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calendar'])[1]/following::div[8]</value>
      <webElementGuid>05046ef5-8759-42c2-bf12-6aeecc153f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div[2]</value>
      <webElementGuid>7eaad5ff-5b81-4dcd-93c8-f91b852279f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'row2' and (text() = 'ORSelect filesChoose file' or . = 'ORSelect filesChoose file')]</value>
      <webElementGuid>2ee567ac-d3f3-4839-819e-e010e0d7c99e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
