<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>line</name>
   <tag></tag>
   <elementGuidId>f5835bff-671a-4f3e-984c-0d4dbe5bf6b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>line</value>
      <webElementGuid>ad84bce7-57b9-41e6-a00c-cb42864bad07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x1</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>630f9164-ebf4-487f-ad98-160c86801707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y1</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>a34b89a6-4055-4027-b0e8-379c3715ee96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x2</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>1086e300-4b1c-465b-9e3e-4f8a6d6acea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y2</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>cab08423-da2a-4a1f-a0fd-601de21ff72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-hide&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/app-navbar[@class=&quot;header-navbar navbar navbar-expand-lg align-items-center navbar-shadow navbar-light floating-nav container-xxl ng-star-inserted&quot;]/div[@class=&quot;navbar-container d-flex content&quot;]/div[@class=&quot;bookmark-wrapper d-flex align-items-center&quot;]/ul[@class=&quot;nav navbar-nav d-xl-none ng-star-inserted&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link menu-toggle&quot;]/svg[@class=&quot;feather feather-menu ficon&quot;]/line[2]</value>
      <webElementGuid>ac519a7f-6cd3-43ef-a39d-f33cff8b0e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>line</value>
      <webElementGuid>8f4054df-6000-444a-84f0-fdbadc710c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x1</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>daed38f3-3553-4123-a211-1bcf74324dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y1</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>edd1f470-0961-48ff-a59b-540a80474785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x2</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>f7df0f76-934e-45a2-af3a-95ed0e1a13a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y2</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>2ea92b32-8650-4e4b-a65b-97e85a1002c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/app-navbar[@class=&quot;header-navbar navbar navbar-expand-lg align-items-center navbar-shadow navbar-light floating-nav container-xxl ng-star-inserted&quot;]/div[@class=&quot;navbar-container d-flex content&quot;]/div[@class=&quot;bookmark-wrapper d-flex align-items-center&quot;]/ul[@class=&quot;nav navbar-nav d-xl-none ng-star-inserted&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link menu-toggle&quot;]/svg[@class=&quot;feather feather-menu ficon&quot;]/line[2]</value>
      <webElementGuid>d1bdd044-e2c7-4cca-88c3-3e6db4606529</webElementGuid>
   </webElementProperties>
</WebElementEntity>
