<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ngb-highlight_filetype</name>
   <tag></tag>
   <elementGuidId>7fa266ab-6d77-4d84-ab80-16733f4f04b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ngb-typeahead-0-0']/ngb-highlight</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ngb-highlight.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ngb-highlight</value>
      <webElementGuid>5e17204b-4152-4323-8879-ac557b90e860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>3eeeb494-68d2-4ff8-820a-88b828a1cfe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>filetype</value>
      <webElementGuid>0f5060f0-06b0-471a-975e-f776ee73b644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngb-typeahead-0-0&quot;)/ngb-highlight[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>7a383bed-0d5c-49b8-b655-e7b671c42d2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='ngb-typeahead-0-0']/ngb-highlight</value>
      <webElementGuid>c2fec18c-2249-4d5c-98d9-2df17616c3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Key'])[1]/following::ngb-highlight[1]</value>
      <webElementGuid>558e3c02-62f8-4873-90c1-34a2339415c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='preet.zip'])[1]/following::ngb-highlight[1]</value>
      <webElementGuid>c6f29f3b-95b8-4bc4-b7de-be45e4fc7db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assay_Type'])[1]/preceding::ngb-highlight[1]</value>
      <webElementGuid>d0df2194-1f4b-4894-9d1f-a62793e27e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LibrarySelection'])[1]/preceding::ngb-highlight[2]</value>
      <webElementGuid>fb70eaaa-5b03-4e47-b79f-0d2b5a72cfa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='filetype']/parent::*</value>
      <webElementGuid>bbd98308-acf6-4e6d-8b2b-56ff512afca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ngb-highlight</value>
      <webElementGuid>dab13a89-ce14-41fc-9a0d-1888de1febc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ngb-highlight[(text() = 'filetype' or . = 'filetype')]</value>
      <webElementGuid>c4a89cda-527b-41d2-8398-5da0297c8ca0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
