<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Users</name>
   <tag></tag>
   <elementGuidId>75eda7c5-2aba-4c76-91c7-5c4b615387d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Storage'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c4cde55c-4a7d-4865-aff2-1d78771d1a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-title text-truncate ng-star-inserted</value>
      <webElementGuid>3b209fff-9e3d-4a77-b71b-35d0bd41bfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users</value>
      <webElementGuid>4933a646-62ed-4b36-9463-fa2b846e295a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-open&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/core-sidebar[@class=&quot;main-menu menu-fixed menu-accordio menu-shadow menu-light ng-star-inserted&quot;]/app-menu[@class=&quot;vertical-menu&quot;]/vertical-menu[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-menu-content ps&quot;]/ul[@class=&quot;navigation navigation-main&quot;]/li[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;d-flex align-items-center ng-star-inserted&quot;]/span[@class=&quot;menu-title text-truncate ng-star-inserted&quot;]</value>
      <webElementGuid>8cb53b00-4ebc-479f-901c-229d635dd93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>68c93375-9231-475e-9eca-5244bee32c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-title text-truncate ng-star-inserted</value>
      <webElementGuid>305828cd-e3e9-416f-b30e-e51c64d477a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users</value>
      <webElementGuid>04838760-1219-4d7c-87ac-4b3f502fb5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-open&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/core-sidebar[@class=&quot;main-menu menu-fixed menu-accordio menu-shadow menu-light ng-star-inserted&quot;]/app-menu[@class=&quot;vertical-menu&quot;]/vertical-menu[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;main-menu-content ps&quot;]/ul[@class=&quot;navigation navigation-main&quot;]/li[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;d-flex align-items-center ng-star-inserted&quot;]/span[@class=&quot;menu-title text-truncate ng-star-inserted&quot;]</value>
      <webElementGuid>c7b80544-f3b9-4af5-8934-f1b25c746dad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Storage'])[1]/following::span[1]</value>
      <webElementGuid>17c86217-c0bb-49b3-a68e-bc4333c2d65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::span[2]</value>
      <webElementGuid>7eacb76e-a9ac-49f6-8061-6e06db94d3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vcf'])[1]/preceding::span[1]</value>
      <webElementGuid>174425de-5808-42ec-a9c1-8749089379a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::span[2]</value>
      <webElementGuid>457ac898-3804-4185-b7c6-faf4af296983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Users']/parent::*</value>
      <webElementGuid>03512da6-49cf-4d64-9bd1-6f9925c7f84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span</value>
      <webElementGuid>e5b01469-a362-4dec-86ce-505c09015c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Users' or . = 'Users')]</value>
      <webElementGuid>1bf9d97b-7336-4fb2-9728-1597a2605fee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
