<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Pages_feather feather-menu ficon</name>
   <tag></tag>
   <elementGuidId>8b65ce00-b93d-47a8-9e20-51e5e9a0c12e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.feather.feather-menu.ficon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Pages'])[1]/preceding::*[name()='svg'][4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>61f4c28c-a3fb-4126-bb31-0656653df040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>349442d7-9d42-4739-8803-7649e82131e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>8d9167ba-08d4-4de8-a160-9e98d9d2731a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>ed17ba5e-d5ea-44d5-81a5-0da5c30464e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>2c984c63-38bf-4e52-aa6f-c1f369dec500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>66bf6fa2-d2d6-4f07-a467-5b5bf918ec54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>72190356-32b7-4cbe-b73e-831a454b2c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0c003475-3410-4ce3-a087-1723ca10237f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>272b36f3-0b6a-4a57-b049-c4b3136d896a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>2c6ad2aa-9489-40ed-a793-e2c077290136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-menu ficon</value>
      <webElementGuid>d0c9df1f-ffab-4751-a148-f3d2532250b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/app-navbar[@class=&quot;header-navbar navbar navbar-expand-lg align-items-center navbar-shadow navbar-light floating-nav container-xxl ng-star-inserted&quot;]/div[@class=&quot;navbar-container d-flex content&quot;]/div[@class=&quot;bookmark-wrapper d-flex align-items-center&quot;]/ul[@class=&quot;nav navbar-nav d-xl-none ng-star-inserted&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link menu-toggle&quot;]/svg[@class=&quot;feather feather-menu ficon&quot;]</value>
      <webElementGuid>5a377561-d7e6-4ed5-ab64-abdd19d71d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>ec127b3c-6614-4ec4-be74-721316ab0622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>6f77be1d-afaa-41fe-8546-486e63136f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>20085662-535e-4561-b2e7-eac2bf10ca0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>254428ea-d354-498d-806c-ebd65bce1363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>458ccedb-c859-4145-9f83-e54a2b5eab17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>dd1a95f4-746c-4cc6-adad-e27cd1ebf880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>b9ad0ba1-4a11-4c84-952f-147e1d276bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c2c3b682-a4c9-4c17-93ac-557ed2061bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>25e6b408-1c19-4819-9e04-f5bb6b03f1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>93c36444-df8d-4939-942b-b178083a1ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-menu ficon</value>
      <webElementGuid>4e5f8df9-1f10-46ae-aa00-aeb2a8f28252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/app-navbar[@class=&quot;header-navbar navbar navbar-expand-lg align-items-center navbar-shadow navbar-light floating-nav container-xxl ng-star-inserted&quot;]/div[@class=&quot;navbar-container d-flex content&quot;]/div[@class=&quot;bookmark-wrapper d-flex align-items-center&quot;]/ul[@class=&quot;nav navbar-nav d-xl-none ng-star-inserted&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link menu-toggle&quot;]/svg[@class=&quot;feather feather-menu ficon&quot;]</value>
      <webElementGuid>57564d48-9181-419f-9e24-48230560741d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>33e4a451-ed55-4a56-b5f0-56ca7b2bbad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>916bbf61-79d3-41a7-9ce8-fdd0ae23a4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>2c571543-fbac-4cfb-a774-4b7026fc11f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>208a1043-7d7a-4305-bd6a-534fca8e5571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>6a680483-16e8-4b18-bd7e-2c1dd9c74734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>89a5de5a-dd69-4203-a182-c802d00b3e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>f60d9372-781b-4ef2-ad29-e6c201f5f638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c5080c11-1f72-47c9-9978-8d8de6e6cf58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>f95a1e6c-c56f-4a12-9b06-7e09c38aff81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>796ec35d-660d-489f-953d-e244612ffb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-menu ficon</value>
      <webElementGuid>be88e556-c89c-4614-9fc6-8aef78433df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/app-navbar[@class=&quot;header-navbar navbar navbar-expand-lg align-items-center navbar-shadow navbar-light floating-nav container-xxl ng-star-inserted&quot;]/div[@class=&quot;navbar-container d-flex content&quot;]/div[@class=&quot;bookmark-wrapper d-flex align-items-center&quot;]/ul[@class=&quot;nav navbar-nav d-xl-none ng-star-inserted&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link menu-toggle&quot;]/svg[@class=&quot;feather feather-menu ficon&quot;]</value>
      <webElementGuid>68bce571-e230-4c34-8c7e-a9aabc699332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>fcc053e6-18a8-409c-b744-26677835ce60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>f0860c16-0f78-4d5b-ad65-415b46923f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>83bcf76b-ec37-46ad-82c5-25cf665a2dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>e9dda155-e145-48c2-8d70-df3df97a1ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>6e67cf3d-c0a6-4f6e-93a0-dd3a4e0b7a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>d446eb2b-eecc-445c-b877-3fa2ef70d1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>9e19ad2a-ba54-40fc-872e-19cd7b9f7871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d60d66b6-f04e-4bf7-83bf-836ea35632c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>63ab0ba0-18bd-4513-a2e5-2bcf92577582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>dbe3b0d9-ded5-403e-ab89-2b587c39091c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-menu ficon</value>
      <webElementGuid>224a7ffb-6f90-4a23-9584-8acae701c8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/app-navbar[@class=&quot;header-navbar navbar navbar-expand-lg align-items-center navbar-shadow navbar-light floating-nav container-xxl ng-star-inserted&quot;]/div[@class=&quot;navbar-container d-flex content&quot;]/div[@class=&quot;bookmark-wrapper d-flex align-items-center&quot;]/ul[@class=&quot;nav navbar-nav d-xl-none ng-star-inserted&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link menu-toggle&quot;]/svg[@class=&quot;feather feather-menu ficon&quot;]</value>
      <webElementGuid>a39589d1-e19d-4961-942b-aaa02018b0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>a2eea218-aefe-4596-b0ff-3d8506cdd1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>ecf92019-0da7-46ea-8555-6fe090725711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>93ad2382-b8d5-4134-aeb2-772f8b2a73ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>d99c6785-21a7-4dfa-913e-689c489fe7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>3f06c619-3e82-4d11-b0f6-8a6eefa55e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>1156989c-5fd8-4db1-91a3-f95d005d3a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>c7f21dd4-9731-4d73-ac2b-84ef30d0489e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>260e8d5a-8721-471e-88c4-9518026bad33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>7b8f64e5-0bd9-41b2-a7fa-8bc58ce2b2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>ca2f6297-8e64-49db-be75-ec322602887c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-menu ficon</value>
      <webElementGuid>e4932641-63e1-45c0-9058-894db41b5302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/app-navbar[@class=&quot;header-navbar navbar navbar-expand-lg align-items-center navbar-shadow navbar-light floating-nav container-xxl ng-star-inserted&quot;]/div[@class=&quot;navbar-container d-flex content&quot;]/div[@class=&quot;bookmark-wrapper d-flex align-items-center&quot;]/ul[@class=&quot;nav navbar-nav d-xl-none ng-star-inserted&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link menu-toggle&quot;]/svg[@class=&quot;feather feather-menu ficon&quot;]</value>
      <webElementGuid>03c9db94-0176-4d88-a7c9-40216a803f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>c7effd8e-7734-4cb8-b25f-cdf05ecef5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>8d2600c3-4185-4bd6-b1bf-35a3ccfd7fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>0783793e-8169-4590-bb47-9889553385b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>b23b38bd-b370-45c3-bd95-31a0023a4d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>661b6359-8898-4208-a6a3-b0eb71b0dcfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a4e697b3-128e-45c4-86b7-b0e6d31e7f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>fe6c4880-d72c-469e-92cd-7b5b87b2fdc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>76e5aac3-c219-418e-a658-6255a9383f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>043390b0-1859-42c3-a653-6d55bbd41124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>8435d698-e096-4721-b359-bf670396fe2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-menu ficon</value>
      <webElementGuid>cbaef92f-e215-4b6a-90a9-084b470a9fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/app-navbar[@class=&quot;header-navbar navbar navbar-expand-lg align-items-center navbar-shadow navbar-light floating-nav container-xxl ng-star-inserted&quot;]/div[@class=&quot;navbar-container d-flex content&quot;]/div[@class=&quot;bookmark-wrapper d-flex align-items-center&quot;]/ul[@class=&quot;nav navbar-nav d-xl-none ng-star-inserted&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link menu-toggle&quot;]/svg[@class=&quot;feather feather-menu ficon&quot;]</value>
      <webElementGuid>813a5e22-1037-425b-a144-a7f90f90e4c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pages'])[1]/preceding::*[name()='svg'][4]</value>
      <webElementGuid>3fe90523-e4a9-4e63-9557-26318618956b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results found.'])[1]/preceding::*[name()='svg'][5]</value>
      <webElementGuid>6d982103-616e-4e76-a152-5f85dc90be22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
