<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_jamsandekar_feather feather-edit cursor_5f0fbd</name>
   <tag></tag>
   <elementGuidId>2838c8d5-4fc8-4b92-9494-0546a48085bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='jamsandekar'])[2]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>7a4c81d8-ad03-4f3b-88cf-7bd4e655b055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>d85c1d97-7d7c-4d2a-8ee7-2666fe915197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>452dba97-f29b-4fb9-a9db-1db695eb6dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>548640c2-2215-48bc-a6f0-33f0f53727d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>8ecd1803-43f0-4adb-8d68-3394b3f6983b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>14286379-3c80-4ec1-a944-12fd75c5e51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>e8085ad0-3801-4e11-bc7e-7dd90ec3ea8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7bcc78af-72ac-4988-8249-3c6c98003157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>bb876eff-4679-4b5e-91e8-0ab560742888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>1efd3fbf-eef4-42b3-96ae-c2814e6ba5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-edit cursor-pointer</value>
      <webElementGuid>04c8b739-13c0-4610-88fb-04f46d0973c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-hide&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-content content&quot;]/content[@class=&quot;ng-tns-c118-1 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c118-1 ng-trigger ng-trigger-zoomIn&quot;]/app-user-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content-wrapper container-xxl p-0&quot;]/div[@class=&quot;content-body&quot;]/section[@class=&quot;users-list-wrapper&quot;]/div[@class=&quot;card mb-3 lg-3 xs-3&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-sm mb-0&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[5]/button[@class=&quot;btn icon-btn waves-effect waves-float waves-light&quot;]/a[1]/svg[@class=&quot;feather feather-edit cursor-pointer&quot;]</value>
      <webElementGuid>fbdf6a03-2524-4d61-9d39-15269823b7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>34c2cc9a-cc45-4896-9029-b03219f82043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>3577e68e-1f53-4be0-aa5f-36f647524927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>8ea534f6-6fdf-4d41-bdde-38db3fe16a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>dcb7e568-8a51-44ad-b252-206deaa057eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>62ab6850-b48f-466f-be71-b9771fb26566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>944137c9-4b7b-444a-a2bd-c7a84b2479ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>382b1c44-37ba-49d5-a851-b9db55f4a9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0e2b3a28-955c-4c12-ab06-7e15587ea3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>40a34443-d2f2-4c3e-84ef-560fb5185106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>fcf76886-b72a-4b42-a17b-e5805844aa11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-edit cursor-pointer</value>
      <webElementGuid>7a33c282-4b4b-4bd8-b537-ce116af924e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-hide&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-content content&quot;]/content[@class=&quot;ng-tns-c118-1 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c118-1 ng-trigger ng-trigger-zoomIn&quot;]/app-user-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content-wrapper container-xxl p-0&quot;]/div[@class=&quot;content-body&quot;]/section[@class=&quot;users-list-wrapper&quot;]/div[@class=&quot;card mb-3 lg-3 xs-3&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-sm mb-0&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[5]/button[@class=&quot;btn icon-btn waves-effect waves-float waves-light&quot;]/a[1]/svg[@class=&quot;feather feather-edit cursor-pointer&quot;]</value>
      <webElementGuid>e04476ea-d0f4-494c-9f33-d382fcb20c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>c1a79f82-af3b-4b9e-9465-b8b128000e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>f0bd4315-d7d4-4e81-b63b-028b63680257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>153e9f2e-1d96-47b5-8998-b3f2b1a4c23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>3913cf6b-2257-4ef9-907d-d2e7db5ef7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>c5bd4e6d-79d8-4b88-98af-aff696d26d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>67a265ed-bd15-465a-a083-0b66a9bbd7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>0d87f4f0-3316-4ad8-aaa2-9061688aca42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7a5582e4-aca3-457d-a275-6ecf8cd060c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>726a512b-e163-4a1d-9443-7cb392da49d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>9de18bac-dc27-429d-84e6-4b46647870fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-edit cursor-pointer</value>
      <webElementGuid>0052d89b-4a39-457b-9370-6e28d54cfecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-hide&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-content content&quot;]/content[@class=&quot;ng-tns-c118-1 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c118-1 ng-trigger ng-trigger-zoomIn&quot;]/app-user-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content-wrapper container-xxl p-0&quot;]/div[@class=&quot;content-body&quot;]/section[@class=&quot;users-list-wrapper&quot;]/div[@class=&quot;card mb-3 lg-3 xs-3&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-sm mb-0&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[5]/button[@class=&quot;btn icon-btn waves-effect waves-float waves-light&quot;]/a[1]/svg[@class=&quot;feather feather-edit cursor-pointer&quot;]</value>
      <webElementGuid>0fd8ef7f-02ea-4c8c-9d5d-61dd5916f021</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jamsandekar'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>26305bb6-7efc-42d3-95a9-b6267d684a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sunil'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>2bbb34bb-88aa-4048-b4c8-ae53ef61d6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>fb4a8616-6dcd-42c2-91af-5980ea358a47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
