<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Pages_feather feather-menu ficon_1</name>
   <tag></tag>
   <elementGuidId>aa6ccc70-2cf4-4974-bb53-072d87370c53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Pages'])[1]/preceding::*[name()='svg'][4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.feather.feather-menu.ficon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>456f7495-8028-4cc6-baa2-821fff87403d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>de9e679b-c630-4aae-a80d-5a8219db417a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>25ae4349-4f9a-49aa-ab1e-c3e07a14a75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>0b3063c0-7c99-4a6f-a8c3-ba4442b42c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>9a425d4c-fa2c-4f39-83db-2aad7bf94950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>5e6d242f-d018-4282-a63f-9e6b51248b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>923d1836-e0ae-47ea-9aee-ffa3bdeb3d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ef60a56b-e800-43c5-bc7d-f4ef7ccea50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>f3944f2b-9fef-43d0-92ef-f7d52bfac0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>8382ef08-1aa4-4557-b0d4-e2bdbfe0400a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-menu ficon</value>
      <webElementGuid>142e7710-8f6e-4d9a-88dc-b402a9b6b8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-hide&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/app-navbar[@class=&quot;header-navbar navbar navbar-expand-lg align-items-center navbar-shadow navbar-light floating-nav container-xxl ng-star-inserted&quot;]/div[@class=&quot;navbar-container d-flex content&quot;]/div[@class=&quot;bookmark-wrapper d-flex align-items-center&quot;]/ul[@class=&quot;nav navbar-nav d-xl-none ng-star-inserted&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link menu-toggle&quot;]/svg[@class=&quot;feather feather-menu ficon&quot;]</value>
      <webElementGuid>79adead8-92fa-46b6-aad3-5dc38f03c21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>cbe08ec9-06d9-49dd-b13c-444b6926bb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>240c625b-e60c-4b05-87d4-8e14e37a7540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>927c5c3d-3659-49dc-b498-08d2026a0f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>5bb136ac-3257-4c0f-88f9-057eb5c5009c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>352a7ec1-093c-4319-b9c2-d8fec0874838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>dbfe31e3-bb6f-496f-91c1-4ffbf9626b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>4068001e-8820-4273-a753-a74f14ff5bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>fd2a9d53-689b-4253-ac6a-db7ec13c8c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>0662f477-1f85-45ff-adb9-2713d8d159de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>fa7c81c3-e110-486b-85f9-1f1a127c99f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-menu ficon</value>
      <webElementGuid>3bf83057-8092-4651-a3f1-0773586fcd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-hide&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/app-navbar[@class=&quot;header-navbar navbar navbar-expand-lg align-items-center navbar-shadow navbar-light floating-nav container-xxl ng-star-inserted&quot;]/div[@class=&quot;navbar-container d-flex content&quot;]/div[@class=&quot;bookmark-wrapper d-flex align-items-center&quot;]/ul[@class=&quot;nav navbar-nav d-xl-none ng-star-inserted&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link menu-toggle&quot;]/svg[@class=&quot;feather feather-menu ficon&quot;]</value>
      <webElementGuid>d52081b0-a5ae-415f-8090-46877deedb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>309bf03a-e8e3-47fd-900f-0e02953cd4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>96e87f9c-373e-469d-a92b-337ac6bcadba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>1413f64c-3357-4913-aecd-f495e1e1f8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>0447b6f2-5ae2-4a2c-aa84-8ca685b0c20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>145fba43-5881-4cc4-a3fc-331bc872dbbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a4a3f58e-5835-4a28-92d6-a46fe3771b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>00d8b165-2418-4565-b589-e213607c4a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4d1a90b4-5f99-4801-ad02-02d6783bf40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>be734d3d-b197-4bae-8b33-beebefa05ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>aa0c26e7-d906-4d1f-86ec-e4e8253ebd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-menu ficon</value>
      <webElementGuid>8e74688b-f92f-4d5e-8900-d97de6a64759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography ng-tns-0-0 default-layout&quot;]/app-root[@class=&quot;vertical-layout navbar-floating footer-static menu-expanded vertical-overlay-menu menu-hide&quot;]/vertical-layout[@class=&quot;ng-star-inserted&quot;]/app-navbar[@class=&quot;header-navbar navbar navbar-expand-lg align-items-center navbar-shadow navbar-light floating-nav container-xxl ng-star-inserted&quot;]/div[@class=&quot;navbar-container d-flex content&quot;]/div[@class=&quot;bookmark-wrapper d-flex align-items-center&quot;]/ul[@class=&quot;nav navbar-nav d-xl-none ng-star-inserted&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link menu-toggle&quot;]/svg[@class=&quot;feather feather-menu ficon&quot;]</value>
      <webElementGuid>404c3d39-2328-4f31-bfac-146b8978fd9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pages'])[1]/preceding::*[name()='svg'][4]</value>
      <webElementGuid>64ff8ff8-bdc6-4459-8db7-3e62cf02ed6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results found.'])[1]/preceding::*[name()='svg'][5]</value>
      <webElementGuid>f316dd80-ca76-436c-9f6d-4731f36d6188</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
