apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -prod

resources:
- ../../base

commonLabels:
  mode: prod

namespace: ice

patchesStrategicMerge:
- rollout-replicas.yaml

images:
- name: hub.bio.pune.cdac.in/dbt/ice-ui-service
  newTag: latest