<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Choose file</name>
   <tag></tag>
   <elementGuidId>f69426a9-8709-4cb4-9251-8dc3fb0b3167</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='row2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#row2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>82df629e-482e-4e36-b92e-3a1208a12e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>row2</value>
      <webElementGuid>172f9821-59d7-4609-8bff-01fb125fb808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ORSelect filesChoose file</value>
      <webElementGuid>d3b2fe4a-454e-49a9-982c-d5260e3d75cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row2&quot;)</value>
      <webElementGuid>52a33060-9125-4ff2-840d-954ea4a03942</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='row2']</value>
      <webElementGuid>422f81e0-4a55-41b8-8b1e-b87ce73f9503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='file-upload']/div/div/div/div[2]/div[2]</value>
      <webElementGuid>27782cfa-2cf2-41b6-b10f-cee764695b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drop Files Here To Upload'])[1]/following::div[1]</value>
      <webElementGuid>f4ca446a-897f-4ca8-a896-8d3579bf4fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calendar'])[1]/following::div[8]</value>
      <webElementGuid>f46ba98b-4f73-4240-9ac6-e55b185d2c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div[2]</value>
      <webElementGuid>57fbb83e-af51-47ca-bf5c-e75f52f377db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'row2' and (text() = 'ORSelect filesChoose file' or . = 'ORSelect filesChoose file')]</value>
      <webElementGuid>e6e34db5-5869-462d-8060-b921b0eb8a4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
