export const environment = {
  production: false,
  hmr: false,
  apiUrl: "https://localhost:5000",
  keycloakUri: "https://ice-dev.bio.pune.cdac.in/auth",
  keycloakClientId: "ice-angular",
  keycloakRealm: "ice",
  baseURL: "https://ice-dev.bio.pune.cdac.in",
  basePath: "https://localhost:5000/",
  log_level: 4,
  websocketUrl: "wss://ice-dev.bio.pune.cdac.in",
  s3Url: "https://s3.bio.pune.cdac.in",
  submissionurl: "https://10.208.27.111:8081",
  computeNamespace: "ice-compute",
};
