apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage 
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaniko-cache-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 20Gi
