apiVersion: v1
kind: Service
metadata:
  name: ice-ui
  labels:
    app: ui-app
spec:
  selector:
    app: ui-app
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: 8080
