apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev

resources:
- ../../base

commonLabels:
  mode: dev

namespace: ice-dev

images:
- name: hub.bio.pune.cdac.in/dbt/ice-ui-service
  newTag: latest
